---
title: "Thoracolumbar Impairments within Hemiparetic Gait"
author: "Mac Prible"
date: "4/4/2020"
output: word_document
bibliography: literature.bib
---

# Introduction 

Hemiparetic gait following a stroke is associated with decreased walking speeds [@Roth1997-nh] and contributes to stroke leading the causes of disability in the United States [@Centers_for_Disease_Control_and_Prevention_CDC2009-hi]. This disability not only places a strain on caregivers [@Anderson1995-ys], it contributes to lower activity levels and increased risk of additional cardiovascular events [@Benjamin2017-no]. 

Attempts to improve walking in individuals with chronic hemiparesis present an ongoing challenge in rehabilitation. Clinical interventions have demonstrated limited efficacy at creating functionally meaningful improvements in gait speed [@Dickstein2008-qs]. 

Studies of the impairments underlying hemiparetic gait routinely focused on deficits in the limbs and peripheral kinematics. This includes plantar flexor weakness  [@Allen2014-ka], dorsiflexor weakness [@Ng2012-yq], step length asymmetry [@Balasubramanian2007-eo], step width asymmetry [@Balasubramanian2010-dq], and hip extension deficits [@Hsiao2016-tr]. 

While stroke-associated deficits in limb function are readily apparent in a clinical setting, less obvious impairments exist in the trunk. This paper explores these impairments in thoracolumbar function following stroke, their relationship to gait, and implications for rehabilitation strategies. 

# Trunk control is an important component in the development of locomotion

Rhythmic movements of the spinal column have been components of vertebrate locomotion dating back to lampreys and have been conserved across a diverse range of animals [@Katz2016-jy]. Case studies of individuals with complete spinal cord injury have indicated not only that central pattern generators related to bipedal locomotion exist in humans [@Dimitrijevic1998-jr], but that they reveal rhythmic spinal motion in addition to rhythmic limb motion [@Bussel1988-ei].

From a developmental perspective, control of the trunk is a critical part of infant motor learning.  While infant development is not linear with mandatory milestones along the way, trunk dominant movements such as rolling and lifting the head while prone precede tasks such as sitting unsupported, crawling, standing, and walking [@Adolph2013-ee].

## Trunk impairments are associated with functional impairment
Beyond having evolutionary and developmental significance, trunk control after a stroke can predict long-term functional outcomes. This has been shown with the Postural Assessment Scale for Stroke - Trunk Component (PASS-TC) [@Hsieh2002-sk]. and the Trunk Control Test (TCT) [@Duarte2002-bm]. 

Hsieh et al. investigated the use of the PASS-TC two weeks after stroke to predict functional disability 6 months after stroke. The PASS-TC generates a composite score to summarize trunk function based on a series of movements: sitting without support, rolling from supine to the side, transfering from supine to sitting, and then back from sitting to supine. When comparing the PASS-TC and Fugl Meyer at two weeks after a stroke, the PASS-TC demonstrated a higher correlation to functional ability 6 months post-stroke. Given that the Fugl Meyer is a more involved measure that can take 30 minutes to administer [@Gladstone2002-dx], this suggests that insight into trunk control provides clinical information with a high degree of functional significance.

Investigation of the Trunk Control Test by Duarte et al. revealed a similar story. The TCT uses a simple set of bed mobility tasks much like the PASS-TC: rolling to either side from supine, sitting up from lying down, and balancing in a sitting position. When assessed upon admission to an inpatient rehab facility, this quickly administered test was predictive of both the Functional Independence Measure and walking speed at discharge.

Both of these assessments capture the level of trunk control following a stroke. Both reveal a relationship between trunk control impairment and long-term functional ability, specifically gait speed in the case of the TCT. This begs the question: what are the specific post-stroke impairments that underly these deficits in rolling and sitting. 

 
# Thoracolumbar Deficits Following Stroke

Post-stroke thoracolumbar impairments present both during direct volitional trunk movement [@Dickstein2004-zc], and during anticipatory postural adjustments of the trunk made prior to limb movement [@Dickstein2004-bu].

To study direct volitional muscle recruitment, Dickstein and colleages had subjects with and without hemiparesis sit up from a reclined position (trunk flexion) and lower their foreheads to a table and back from a seated postion (eccentric and concentric trunk extension). Movements were prompted by an audible cue to understand the timing of the recruitment pattern. EMG activity of superfical trunk muscles (the latissimus dorsi and rectus abdominus) as well as deeper musculature (the external oblique and lumbar erector spinae) were examined. In individuals with hemiparesis, the superficial musculature contralateral to the stroke demonstrated EMG activity deficits and delayed timing onset. While the results for the external oblique were not definitive, the axial trunk extensors (erector spinae) exhibited notable sparing bilaterally. The results suggest that that deeper and more axial musculature may be less affected by stroke while muscles such as the latissums dorsi exhibit a more classic hemiparetic pattern.

Anticipatory postural adjustments are feed-forward changes in muscle activation that provide the necessary bracing and counterbalancing prior to launching more obvious voluntary actions [@Lee1980-qu]. In the second paper in 2004, Dickstein and colleagues examined these adjustments in the trunk prior to lifting an arm or leg. Both the paretic and non-paretic side were studied in individuals with hemiparesis and compared with healthy controls. In a similar outcome to the previous paper, the more superfical and lateral musculature (latissiums doris, rectus abdominus and external oblique) exhibited altered coordination patterns when lifting the limb contralateral to the stroke lesion. Lifting of the limb ipsilateral to the lesion was accompanied by anticipatory adjustments that were similar to healthy controls. In lifting either side, the axial extensors (lumbar erector spinae) appear to be relatively spared.

This sparing of the axial musculature may help to explain the increased bilateral activation of the erector spinae that has been identified in individuals with hemiparesis when performing seated functional activities [@Winzeler-Mercay2002-ug].

Though the more granular impairments appear to be unilateral, the resulting strength impact appears to be multidirectional. Relative weakness has been identified in thoracolumbar flexion and extension [@Tanaka1998-en; @Karatas2004-xm], lateral flexion [@Bohannon1995-eq], and rotation [@Tanaka1997-tp]. Weakness in rotation and lateral flexion is not isolated to one side and appears to manifest equally between the two sides.

All of these strength studies utilize instrumented testing to quantify force production. Tanaka et al. (1998) note that trunk strength deficits are difficult to detect with standard clinical measures such as manual muscle tests. This may in part explain why these impairments receive little focus clinically. 

# Thoracolumbar Movement During Healthy Gait: Speed Matters 

A general framework for understanding thoracolumbar movement during gait comes from @Sartor1999-nu who catalogued the rhythmic trunk movements within the gait cycle. At heel strike, the pelvis was maximally rotated toward the posterior stance leg. As the person entered mid-stance, the pelvis reached maximum lateral tilting, with the hip opposite the stance leg attaining maximum height. While the pelvis moved in a global frame of reference, the spinal movement counteracted this and was able to maintain the thorax in a relatively stable position. 

Later research into healthy gait examined thoracolumbar movement in subjects between the ages of 1 and 16 years [@Thummerer2012-wn]. While sagittal plane movement varied with age (forward tilt increased with age), frontal and transverse movement varied with normalized self-selected speed. Larger amplitude movements were associated with increased normalized speed. As in the research by Sartor, the thorax and pelvis moved opposite each other with the thorax moving minimally in a global frame of reference (typically <2 degrees in the frontal and transverse planes).

In healthy gait, this stable transverse plane counter-rotation emerges after a speed-dependent phase transition that takes place between 0.75 m/s and 1.0 m/s [@Wagenaar1992-nx]. Below that, there is much more variability in the relationship between the thorax and pelvis. Putting this in context, mean self-selected walking speed in healthy adults is typically above 1.2 m/s across sexes and age ranges [@Bohannon1997-mu]. The adults studied by Sartor et al walked at a mean speed of 1.36 m/s. Even at lower speeds the thorax remains relatively stable in a global frame of reference; with increasing speed the pelvis becomes coupled with the movement of the femur creating counter rotation [@Bruijn2008-xy].

@Wagenaar1992-nx suggested this phase transition in a study that compared healthy controls to individuals with hemiparesis. The authors noted that participants with hemiparesis exhibited similar pelvis rotation to healthy controls, though greater ranges of thorax rotation at higher velocities. They associated this increased thoracic movement with increased energy costs. The impaired coordination of the thorax and pelvis may be limiting the ability to transition into higher walking speeds due to progressively less efficient movement patterns. This is particularly important because that phase transition takes place at a critical speed threshold that can seperate community ambulators from individuals who are limited to walking only at home [@Chen2005-xu]. 

# The Head-Arm-Trunk system as a force modulator

In order to appreciate how impaired thorocolumber strength and coordination may affect gait, it is useful to consider the entire coordinated system of the head-arm-trunk (HAT) in the context of step length modulation. Asymmetrical step length is a hallmark of hemiparertic gait, with greater length asymmetry corresponding to asymmetrical force production, slower gait, and more disability [@Balasubramanian2007-eo]. Understanding the mechanisms of this asymmetry may illustrate important factors in hemiparetic gait. 

Increasing step length requires more than just increasing swing time, it requires an increase in propulsive force from the stance limb to be transmitted to the swing limb via the HAT system [@Varraine2000-vf]. 

Within the HAT system, arm swing is an effective strategy to dampen the body's angular momentum [@Bruijn2008-xy]. It is conceivable that maintaining a stable orientation of the axis of arm rotation (the thorax) assists with the efficiency of this dampening mechanism. The stability of the thorax additionally assists with providing a stable platform for the head and teleceptors. Following a stroke, individuals are less able to coordinate counter-rotation between the head and thorax while walking [@Lamontagne2005-hx], suggesting that control of the head and its associated teleceptors may be additionally challenged by impaired control of the thorax.

# Changing the Distal Via the Proximal

The significance of thoracolumbar movement can be validated by showing that proximally targeted interventions can alter distal gait characteristics such as step-length, width, and force production. In a case study of an individual with hemiparesis who exhibited latissimus dorsi spasticity and impaired gait, injection of botulinum toxin to the latissimus dorsi improved the hemiparetic gait pattern [@Li2018-az]. In healthy subjects, constraining the movement between the pelvis and thorax with a worn brace caused a narrowing of step-width and an increased margin of stability while walking [@Arvin2016-fu].

External fixation of the pelvis in the horizontal plane can also change thoracolumbar movement, step-length, and step width [@Veneman2008-qm]. This serves as a warning that gait training with external fixation of the pelvis may not be practicing many of the motor skills required for free walking. This is particulalry important in the context of body-weight supported and robot-assisted gait therapy where external support of the pelvis is a routine component of the intervention. 

# Implications for Robot-Assisted Gait Therapy

In an overview of options for robot-assisted gait therapy, @Morone2017-sg suggest that robotic tools should be chosen based on the degree of a patient’s limitation, with trunk control being a primary consideration. For individuals with low levels of trunk control, these authors advised more restrictive devices that support the trunk. These could be either exoskeletons that control each body segment individually (including the pelvis), or end-effector systems that only control the placement of the feet but provide a hanging support harness. For patients at a higher level of function, less restrictive devices were recommended culminating in simple overground gait training when possible.

A recent Cochrane review of robot assisted gait therapy suggestes that end-effectors devices demonstrate more effectiveness than exoskeletons [@Mehrholz2017-gi]. One possible explanation of this in the context of thoracolumbar control is that end-effector systems allow more freedom of trunk movement and therefore more practice controlling the thorax-pelvis relationship. Devices that more tightly constrain the pelvis and thorax provide limited opportunity to train this component of walking. 

@Aurich-Schuler2019-vg have investigated attempts to improve the effectiveness of the Lokomot, an exoskeleton gait trainer that typically constraints thoracolumbar movement. A new module was introduced that rotates the pelvis in the transverse plane and laterally translates it throughout the gait cycle. Despite this attempt to move the pelvis in a way that is more similar to overground walking, it inverted the thorax-pelvis movement pattern exhibited by healthy subjects in unconstrained walking. This typical pattern involved the pelvis laterally oscillating more widely than the thorax. When using the Lokomot with the FreeD module, the thorax oscillated laterally more widely than the pelvis. This inability to duplicate a natural pattern of walking may be unsurprising given that the movement of the FreeD module ignores frontal plane rotation of the pelvis. Animal models suggest that control of trunk frontal plane rotation can improve stepping kinematics and force production during bipedal gait in animals with induced incomplete spinal cord injury (Moraud et al. 2018). Frontal plane rotation is missing from this module and may be an absent pre-condition before transverse plane rotation coupling occurs at higher speeds.
# Summary

Thoracolumbar function emerges as a potentially significant component of hemiparetic gait. Though post-stroke strength and coordination impairments present contralateral to the lesion in some musculature, multidirectional thoracolumbar weakness emerges as a result. Additional deficits in anticipatory adjustments of the trunk when lifting the paretic limb further undermine the complex dynamic balance requirements of walking. The premise that thoracolumbar function is central to healthy gait is further supported by the ability of trunk control assesments after stroke to predict long term function, in particular gait speed.

An understanding of the typical thoracolumbar movement pattern in healthy walking adds to an appreciation of potential mechanisms at play. Attaining community ambulating speeds requires increasing levels of coordination between the pelvis and thorax in the transverse plane in order to efficiently transmit forces while maintaining stability of the upper body. Frontal plane mechanics at slow walking speeds in healthy humans have not been examined to my knowledge, but animal models suggest these may be important components of force production.

Clinical interventions such as body-weight supported treadmill therapy and robot-assisted gait training routinely constrain the pelvis in space and do not train a skillful management of the thorax-pelvis relationship. This may limit the benefit of these interventions.

# References
